# training configuration
NUM_EPOCHS = 2500
LEARNING_RATE = 2
REG_CONST = 0.0001
NUMERICAL_DELTA = 0.1
EVAL_INTERVAL = 50
FAKE_SAMPLE_SIZE = 20

# network architecture configuration
IMAGE_LENGTH = 28
IMAGE_SIZE = IMAGE_LENGTH * IMAGE_LENGTH
HIDDEN_UNITS = 32
LAYERS_UNITS = [IMAGE_SIZE, HIDDEN_UNITS, 10]
LAYERS_NUM = len(LAYERS_UNITS)
